### ISSUE TITLE
Early loading of external CompUnit::Repository

### ISSUE THREAD

**Issue by ugexe** [perl6/toolchain-bikeshed#1]
Allow an external CompUnit::Repository to be loaded before regular modules such that they are available to attempt loading from an identity matching their short-id. Something like:

`perl6 -CCompUnit::Repository::GitHub -e 'require <github#http://github.com/user/repo.git>; ...'`

or the example in the old s22:

`CompUnitRepo::GitHub#masak/html-template`

Can this be accomplished with CompUnit::Loader if the proper initialization bits are placed in ModuleLoader.nqp? Or will such an external CompUnit::Repository require its own CompUnit::Loader as well?

**Comment by niner** [comment]
CompUnit::Loader could do this just fine. What would be nice was a way to load the CompUnit::Repository implementation while still retaining the precompilation ability. Right now once you change the $*REPO chain after a module has been loaded already, we have to disable precomp completely.
